name: revivals
description: "A new Flutter project."
publish_to: 'none'
version: 6.0.0+6

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_share: ^2.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  syncfusion_flutter_datepicker: ^27.2.3
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  country_code_picker: ^3.0.0
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  pluralize: ^0.0.8
  flutter_date_range_picker: ^0.1.1
  mailer: ^6.1.2
  flutter_secure_storage: ^9.2.2
  flutter_signin_button: ^2.0.0
  app_tracking_transparency: ^2.0.6
  flutter_spinkit: ^5.2.1
  auto_size_text: ^3.0.0
  intl_phone_field: ^3.2.0
  basic_utils: ^5.7.0
  accordion: ^2.6.0
  flutter_rounded_date_picker: ^3.0.4
  calendar_date_picker2: ^1.1.6
  country_picker: ^2.0.26
  country_flags: ^3.0.0
  country_icons: ^3.0.0
  flutter_switch: ^0.3.2
  flutter_inset_box_shadow: ^1.0.8
  badges: ^3.1.2
  password_strength_checker: ^1.2.4
  dropdown_button2: ^2.3.9
  booking_calendar: ^1.1.10
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6
  numpad_layout: ^0.0.3
  rename_app: ^1.6.1
  syncfusion_flutter_charts: ^27.2.5
  animated_digit: ^3.2.3
  flutter_native_splash: ^2.4.1
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

dependency_overrides:
  intl: ^0.19.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/uc_icon.png"

flutter:
  uses-material-design: true

  fonts:
      - family: Lovelo
        fonts:
          - asset: assets/fonts/lovelo_black.otf
          # - asset: assets/fonts/league_spartan.otf
          # - asset: assets/fonts/quicksand.otf

  assets:
      - assets/login/
      - assets/logos/
      - assets/img/items/
      - assets/img/items2/
      - assets/img/backgrounds/
      - assets/img/icons/

flutter_native_splash:
  android: true
  ios: true

  background_image: "assets/logos/beige_background.png"
  branding: "assets/logos/unearthed_logo_3.png"

  android_12: 
    color: "#ebe2e2"
    image: "assets/logos/revive.png"
    branding: "assets/logos/unearthed_logo_3.png"